--1
USE movies

SELECT m.TITLE, m.YEAR, m.LENGTH FROM MOVIE AS m
WHERE m.LENGTH>120 AND m.YEAR<2000 OR LENGTH IS NULL

--2
SELECT ms.NAME, ms.GENDER FROM MOVIESTAR AS ms
WHERE ms.NAME LIKE 'J%' AND ms.BIRTHDATE>1948
ORDER BY ms.NAME DESC

--3
SELECT m.STUDIONAME, COUNT(DISTINCT ss.STARNAME) AS num_actors FROM MOVIE AS m
JOIN STARSIN as ss ON m.TITLE = ss.MOVIETITLE
GROUP BY m.STUDIONAME

--4
SELECT ms.NAME, ISNULL(COUNT(ss.MOVIETITLE), 0) AS num_movies FROM MOVIESTAR AS ms
LEFT JOIN STARSIN AS ss ON ms.NAME = ss.STARNAME
GROUP BY ms.NAME

--5
SELECT s.NAME, m.TITLE, m.YEAR FROM STUDIO AS s
JOIN MOVIE AS m ON s.NAME = m.STUDIONAME
WHERE m.TITLE = (SELECT TOP 1 m2.TITLE FROM MOVIE AS m2
WHERE m2.STUDIONAME = s.NAME 
ORDER BY m2.YEAR DESC)

--6
SELECT TOP 1 ms.NAME FROM MOVIESTAR AS ms
WHERE ms.GENDER = 'M'
ORDER BY ms.BIRTHDATE DESC

--7 wtf
SELECT s.STUDIONAME, s.STARNAME, s.num_movies
FROM (
    SELECT m.STUDIONAME, ss.STARNAME, COUNT(*) AS num_movies
    FROM MOVIE AS m
    JOIN STARSIN AS ss ON m.TITLE = ss.MOVIETITLE
    GROUP BY m.STUDIONAME, ss.STARNAME
) AS s
WHERE s.num_movies = (
    SELECT MAX(s2.num_movies)
    FROM (
        SELECT m2.STUDIONAME, ss2.STARNAME, COUNT(*) AS num_movies
        FROM MOVIE AS m2
        JOIN STARSIN AS ss2 ON m2.TITLE = ss2.MOVIETITLE
        GROUP BY m2.STUDIONAME, ss2.STARNAME
    ) AS s2
    WHERE s2.STUDIONAME = s.STUDIONAME
)
ORDER BY s.STUDIONAME

--8
SELECT ss.MOVIETITLE, ss.MOVIEYEAR, COUNT(*) AS num_actors FROM STARSIN AS ss
GROUP BY ss.MOVIETITLE, ss.MOVIEYEAR
HAVING COUNT(*) > 2

--1
USE ships

SELECT DISTINCT o.SHIP FROM OUTCOMES AS o
WHERE o.SHIP LIKE 'C%' OR  o.SHIP LIKE 'K%' 

--2
SELECT s.NAME, c.COUNTRY  FROM SHIPS AS s
LEFT JOIN CLASSES AS c ON s.CLASS = c.CLASS
LEFT JOIN OUTCOMES AS o ON o.SHIP = s.NAME
WHERE o.RESULT <> 'sunk' OR o.RESULT IS NULL

--3
SELECT c.COUNTRY, ISNULL(COUNT(o.RESULT), 0) AS num_sunk_ships FROM CLASSES AS c
LEFT JOIN SHIPS AS s ON s.CLASS = c.CLASS
LEFT JOIN OUTCOMES AS o ON o.SHIP = s.NAME
GROUP BY c.COUNTRY, o.RESULT
HAVING o.RESULT = 'sunk' OR (o.RESULT IS NULL AND c.COUNTRY NOT IN 
(SELECT c2.COUNTRY FROM CLASSES AS c2
JOIN SHIPS AS s2 ON s2.CLASS = c2.CLASS
JOIN OUTCOMES AS o2 ON o2.SHIP = s2.NAME
WHERE o2.RESULT = 'sunk'))

--4
SELECT b.NAME FROM BATTLES AS b
JOIN OUTCOMES AS o ON o.BATTLE = b.NAME
GROUP BY b.NAME
HAVING COUNT(*) > (SELECT COUNT(*) FROM BATTLES AS b
JOIN OUTCOMES AS o ON o.BATTLE = b.NAME
GROUP BY b.NAME
HAVING b.NAME = 'Guadalcanal')

--5
SELECT b.NAME FROM BATTLES AS b
JOIN OUTCOMES AS o ON o.BATTLE = b.NAME
JOIN SHIPS AS s ON s.NAME = o.SHIP
JOIN CLASSES AS c ON c.CLASS = s.CLASS
GROUP BY b.NAME
HAVING COUNT(DISTINCT s.NAME) >
(SELECT COUNT(*)FROM BATTLES AS b
JOIN OUTCOMES AS o ON o.BATTLE = b.NAME
JOIN SHIPS AS s ON s.NAME = o.SHIP
JOIN CLASSES AS c ON c.CLASS = s.CLASS
GROUP BY b.NAME
HAVING b.NAME = 'Surigao Strait')

--6
SELECT s.NAME, c.DISPLACEMENT, c.NUMGUNS FROM SHIPS AS s
JOIN CLASSES AS c ON s.CLASS = c.CLASS
WHERE c.DISPLACEMENT = (SELECT MIN(c2.DISPLACEMENT) FROM CLASSES AS c2)
AND c.NUMGUNS >=
(SELECT MAX(c3.NUMGUNS) FROM SHIPS AS s2
JOIN CLASSES AS c3 ON s2.CLASS = c3.CLASS
WHERE c3.DISPLACEMENT = (SELECT MIN(c4.DISPLACEMENT) FROM CLASSES AS c4))

--7
SELECT COUNT(*) AS num_ships FROM BATTLES AS b
JOIN OUTCOMES AS o ON o.BATTLE = b.NAME
GROUP BY o.SHIP, o.RESULT, b.DATE
HAVING o.RESULT = 'damaged' AND o.SHIP IN 
(SELECT o2.SHIP FROM BATTLES AS b2
JOIN OUTCOMES AS o2 ON o2.BATTLE = b2.NAME
WHERE o.RESULT<>'sunk' AND b2.DATE>b.DATE)

--8 idfk
SELECT o.SHIP FROM BATTLES AS b
JOIN OUTCOMES AS o ON o.BATTLE = b.NAME
GROUP BY o.SHIP, o.RESULT, b.DATE, b.NAME
HAVING o.RESULT = 'damaged' AND o.SHIP IN
(SELECT o2.SHIP FROM BATTLES AS b2
 JOIN OUTCOMES AS o2 ON o2.BATTLE = b2.NAME
 WHERE o2.RESULT = 'ok' 
   AND b2.DATE > b.DATE 
   AND o2.SHIP = o.SHIP
   AND (
     SELECT COUNT(*) 
     FROM OUTCOMES AS o3 
     WHERE o3.BATTLE = b2.NAME
   ) > (
     SELECT COUNT(*) 
     FROM OUTCOMES AS o3 
     WHERE o3.BATTLE = b.NAME
   )
)

--1
USE pc

SELECT l.model, l.code, l.screen FROM laptop AS l
GROUP BY l.model, l.code, l.screen
HAVING (l.screen = 11 AND l.model IN (SELECT l2.model FROM laptop AS l2
WHERE l2.screen = 15)) OR (l.screen = 15 AND l.model IN (SELECT l3.model FROM laptop AS l3
WHERE l3.screen = 11))

--2
SELECT DISTINCT pc.model FROM pc
JOIN product AS p ON pc.model = p.model
WHERE pc.price < (SELECT MIN(l.price) FROM laptop AS l
JOIN product AS p2 ON l.model = p2.model
WHERE p2.maker = p.maker)

--3
SELECT pc.model, AVG(pc.price) AS avg_price FROM pc
JOIN product AS p ON pc.model = p.model
GROUP BY pc.model, p.maker
HAVING AVG(pc.price) < (SELECT MIN(l.price) FROM laptop AS l
JOIN product AS p2 ON l.model = p2.model
WHERE p2.maker = p.maker)

--4
SELECT pc1.code, p.maker, (SELECT COUNT(*) FROM pc AS pc2 WHERE pc2.price >= pc1.price
GROUP BY pc2.model
HAVING pc2.model = pc1.model) AS num_pc_higher_price
FROM pc AS pc1
JOIN product AS p ON pc1.model = p.model